# Generated by Django 2.0.4 on 2018-06-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('imagen', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='marca',
            field=models.ManyToManyField(to='home.Marca'),
        ),
    ]
