# Generated by Django 2.0.6 on 2018-06-14 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180610_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='marca',
        ),
        migrations.AddField(
            model_name='encuesta',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.Marca'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
    ]
