# Generated by Django 2.0.6 on 2018-06-14 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180613_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='marca',
        ),
        migrations.AddField(
            model_name='marca',
            name='encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='home.Encuesta'),
            preserve_default=False,
        ),
    ]
