# Generated by Django 2.0.6 on 2018-06-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180613_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nIteracion', models.IntegerField()),
                ('encuesta', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.Encuesta')),
            ],
        ),
        migrations.AlterField(
            model_name='marca',
            name='encuesta',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.Encuesta'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(upload_to='home/static'),
        ),
        migrations.AddField(
            model_name='opciones',
            name='marca',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.Marca'),
        ),
    ]
