# Generated by Django 2.0.6 on 2018-06-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180621_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='votos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
