# Generated by Django 2.0.6 on 2018-06-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_marca_votos'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='nIteracion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
