# Generated by Django 2.0.6 on 2018-06-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_encuesta_niteracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='I',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
