# Generated by Django 2.0.6 on 2018-06-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_encuesta_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuesta',
            name='I',
        ),
        migrations.RemoveField(
            model_name='encuesta',
            name='nIteracion',
        ),
    ]
