# Generated by Django 2.0.6 on 2018-06-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20180621_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('edad', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='categoria',
            field=models.CharField(max_length=40),
        ),
    ]
