# Generated by Django 2.0.6 on 2018-06-25 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180624_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
